export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const HANDLE_SORTING = 'HANDLE_SORTING';
export const ERROR = 'ERROR';